export const MAX_FILE_IMAGE_SIZE_MB = 5;
export const MAX_FILE_VIDEO_SIZE_MB = 10;
export const MAX_FILE_IMAGES_SIZE_BYTES = MAX_FILE_IMAGE_SIZE_MB * 1024 * 1024;
export const MAX_FILE_VIDEOS_SIZE_BYTES = MAX_FILE_VIDEO_SIZE_MB * 1024 * 1024;
