export const ROUTER_PATH = {
    HOME: "/",
    ROLE: "/role",
    MEDIA: "/media",
    EMPLOYEE: "/employee",
    CATEGORY: "/category",
    PRODUCT: "/product",
    SERVICE: "/service",
    WORKING: "/working",
    SHIFT: "/shift",
    ORDER: "/order",
    ORDER_PRODUCT: "/order-product",
    ORDER_SERVICE: "/order-service",
    LOGIN: "/login",
};
