export const ROUTER_PATH = {
    HOME: "/",
    ROLE: "/role",
    MEDIA: "/media",
    CLIENT: "/client",
    EMPLOYEE: "/employee",
    CATEGORY: "/category",
    PRODUCT: "/product",
    SERVICE: "/service",
    WORKING: "/working",
    SHIFT: "/shift",
    ORDER: "/order",
    LOGIN: "/login",
    ORGANIZTAION: "/organization",
    SETTING: "/setting",
};
