export enum ETarget {
    MEDIA = "MEDIA",

    PRODUCT = "PRODUCT",
    PRODUCT_DETAIL = "PRODUCT_DETAIL",
    PRODUCT_TYPE = "PRODUCT_TYPE",

    SERVICE = "SERVICE",
    SERVICE_STEP = "SERVICE_STEP",
    SERVICE_EMPLOYEE = "SERVICE_EMPLOYEE",

    EMPLOYEE = "EMPLOYEE",
    USER = "USER",
    CLIENT = "CLIENT",

    ROLE = "ROLE",
    PERMISSION = "PERMISISON",
    ROLE_PERMISSION = "ROLE_PERMISSION",

    ATTRIBUTE = "ATTRIBUTE",
    ATTRIBUTE_VALUE = "ATTRIBUTE_VALUE",
    CATEGORY = "CATEGORY",

    WORKING_HOUR = "WORKING_HOUR",
    SHIFT = "SHIFT",
    SHIFT_EMPLOYEE = "SHIFT_EMPLOYEE",

    ORDER = "ORDER",
    ORGANIZATION = "ORGANIZATION",
}

export enum EAction {
    READ = "READ",
    CREATE = "CREATE",
    UPDATE = "UPDATE",
    DELETE = "DELETE",
}
