export enum ERequestErrorCode {
    BAD_REQUEST = "RE001",
    SERVER_INTERNAL = "RE002",
    FORBIDDEN = "RE003",
    UNAUTHORIZATION = "RE004",
    NOT_FOUND = "RE005",
    INTERNAL_SERVER_ERROR = "RE006",
    UNAUTHORIZED = "RE007",
    BAD_PERMISSION = "RE008",
}
