import { ThemeProvider } from "@/components/theme-prodviders";
import { Toaster } from "@/components/ui/toaster";
import UserClientProvider from "@/context/user.context";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ReactNode } from "react";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    modal,
}: Readonly<{
    children: ReactNode;
    modal: ReactNode;
}>) {
    return (
        <UserClientProvider>
            <html lang="en">
                <body
                    className={cn(
                        "min-h-[100dvh] w-full overflow-x-hidden bg-background font-sans antialiased",
                        inter.variable
                    )}
                >
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        {children}
                        {modal}
                        <Toaster />
                    </ThemeProvider>
                </body>
            </html>
        </UserClientProvider>
    );
}
