import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function HomeLayout({
    hero,
    product,
}: Readonly<{
    hero: React.ReactNode;
    product: React.ReactNode;
}>) {
    return (
        <>
            {hero}
            {product}
        </>
    );
}
