import Navigation from "@/components/navigation";
import UserClientProvider from "@/context/user.context";
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
    product,
}: Readonly<{
    children: React.ReactNode;
    product: React.ReactNode;
}>) {
    return (
        <UserClientProvider>
            <Navigation />
            <main className="w-full h-fit overflow-x-hidden">
                {children}
                {product}
            </main>
        </UserClientProvider>
    );
}
