const configModel = {
    table: {
        addresses: "addresses",
        booking_border_employees: "booking_border_employees",
        booking_border_services: "booking_border_services",
        client: 'client',
        conversation: 'conversation',
        conversation_member: 'conversation_member',
        employee: 'employee',
        employee_image: 'employee_image',
        empoyee_meta: 'empoyee_meta',
        event: 'event',
        event_image: 'event_image',
        event_meta: 'event_meta',
        images: 'images',
        message: 'message',
        order_states: 'order_states',
        order_voucher: 'order_voucher',
        orders: 'orders',
        payrate: 'payrate',
        permissions: 'permissions',
        product: 'product',
        product_image: 'product_image',
        product_meta: 'product_meta',
        product_order_details: 'product_order_details',
        rate_employee: 'rate_employee',
        rate_image: 'rate_image',
        rate_product: 'rate_product',
        rate_service: 'rate_service',
        rating: 'rating',
        role: 'role',
        role_history: 'role_history',
        role_permission: 'role_permission',
        salary_history: 'salary_history',
        service: 'service',
        service_employee: 'service_employee',
        service_image: 'service_image',
        service_meta: 'service_meta',
        transaction: 'transaction',
        user_voucher: 'user_voucher',
        users: 'users',
        voucher_image: 'voucher_image',
        voucher_meta: 'voucher_meta',
        vouchers: 'vouchers'
    }
}

module.exports = configModel;