// Current Index = 45

export enum DataErrorCodeEnum {
    // Internal error
    INTERNAL = 'DE999',

    // Action errors
    CAN_NOT_DO_ACTION = 'DE001',

    // Verification errors
    EMAIL_ALREADY_VERIFIED = 'DE002',

    // Existence errors
    EXIST = 'DE003',
    EXISTED_VOUCHER = 'DE004',
    EXISTED_USERNAME = 'DE005',
    EXISTED_PRODUCT_DETAIL_KEY = 'DE006',
    EXISTED_PRODUCT = 'DE0039',
    EXISTED_PRODUCT_TYPE = 'DE0040',

    // Nonexistence errors
    NOT_EXIST = 'DE007',
    NOT_EXIST_CATEGORY = 'DE008',
    NOT_EXIST_IMAGE = 'DE009',
    NOT_EXIST_VOUCHER = 'DE010',
    NOT_EXIST_EMPLOYEE = 'DE011',
    NOT_EXIST_USER = 'DE012',
    NOT_EXIST_ATTRIBUTE = 'DE013',
    NOT_EXIST_PRODUCT = 'DE014',
    NOT_EXIST_PRODUCT_TYPE = 'DE015',
    NOT_EXIST_MEDIA = 'DE016',
    NOT_EXIST_PRODUCT_DETAIL_KEY = 'DE017',
    NOT_EXIST_ROLE = 'DE042',
    NOT_EXIST_ROLE_PERMISSION = 'DE043',
    NOT_EXIST_PERMISSION = 'DE044',

    // Invalid input errors
    INVALID_ATTRIBUTE_VALUE = 'DE018',
    INVALID_CLIENT_ROLE = 'DE019',
    INVALID_EMAIL = 'DE020',
    INVALID_END_TIME = 'DE021',
    INVALID_FILE = 'DE022',
    INVALID_FILE_TYPE = 'DE023',
    INVALID_OTP = 'DE024',
    INVALID_ROLE = 'DE025',
    INVALID_STAFF_ROLE = 'DE026',
    INVALID_TOKEN = 'DE027',
    INVALID_USER_ROLE = 'DE028',
    INVALID_USER_TYPE = 'DE029',
    INVALID_MEDIA_TYPE = 'DE030',

    // Missing data errors
    MISSING_DATA = 'DE031',
    NO_OTP_TOKEN = 'DE032',
    MISSING_THUMBNAIL = 'DE041',

    // OTP errors
    OTP_EXPIRED = 'DE033',
    OTP_NOT_MATCH = 'DE034',

    // Format errors
    WRONG_FORMAT = 'DE035',
    WRONG_PASSWORD = 'DE036',

    EXPIRED_VOUCHER = 'DE037',
    OUT_OF_USAGE_VOUCHER = 'DE038',

    // Attributes
    ATTRIBUTE_SAME_LEVEL = 'DE045',
}
