export enum PermissionTargetEnum {
    VOUCHER = 'VOUCHER',

    PRODUCT = 'PRODUCT',
    PRODUCT_DETAIL = 'PRODUCT_DETAIL',
    PRODUCT_TYPE = 'PRODUCT_TYPE',

    SERVICE = 'SERVICE',

    EMPLOYEE = 'EMPLOYEE',
    USER = 'USER',
    CLIENT = 'CLIENT',

    ROLE = 'ROLE',
    PERMISSION = 'PERMISISON',
    ROLE_PERMISSION = 'ROLE_PERMISSION',

    ATTRIBUTE = 'ATTRIBUTE',
    ATTRIBUTE_VALUE = 'ATTRIBUTE_VALUE',
    CATEGORY = 'CATEGORY',
}

export enum PermissionActionEnum {
    READ = 'READ',
    CREATE = 'CREATE',
    UPDATE = 'UPDATE',
    DELETE = 'DELETE',
}
